# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Youri-Config
version:      v0.1.0
version_from: lib/Youri/Config.pm
installdirs:  site
requires:
    YAML::AppConfig:               0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30_01
